### ISSUE TITLE
打包后不能运行

### ISSUE THREAD

**Issue by longzaitian** [lovebing/react-native-baidu-map#17]
E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                   Process: com.iprocesstask, PID: 29136
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'com.baidu.mapapi.map.BaiduMap com.baidu.mapapi.map.MapView.getMap()' on a null object reference
                                                       at org.lovebing.reactnative.baidumap.BaiduMapModule.getMap(BaiduMapModule.java:292)
                                                       at org.lovebing.reactnative.baidumap.BaiduMapModule.setMarker(BaiduMapModule.java:99)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
                                                       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:139)
                                                       at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                       at android.os.Handler.handleCallback(Handler.java:815)
                                                       at android.os.Handler.dispatchMessage(Handler.java:104)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                       at android.os.Looper.loop(Looper.java:194)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by lovebing** [comment]
看样子是MapView还没实例化。不要用MapModule的setMarker方法了，能通过js改变MapView属性marker来设置
