### ISSUE TITLE
最新版本不能编译 

### ISSUE THREAD

**Issue by skydeadpeng** [lovebing/react-native-baidu-map#201]
* What went wrong:
A problem occurred evaluating project ':react-native-baidu-map'.
> Could not get unknown property 'ossrhUsername' for object of type org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer.
 提示这个错误。

**Comment by suwu150** [comment]
我也报这个错误,请问怎么解决?

**Comment by lovebing** [comment]
build.gradle 把 uploadArchives 删了

**Comment by skydeadpeng** [comment]
删掉了 还是报错 * What went wrong:
Could not resolve all files for configuration ':react-native-baidu-map:debugCompileClasspath'.
> Could not find com.facebook.react:react-native:0.56.0.

**Comment by lovebing** [comment]
你用react-native是哪个版本？改成你用的版本号

**Comment by suwu150** [comment]
Environment:
  Node: 8.3.0
  Yarn: Not Found
  npm: 5.3.0
  Watchman: Not Found
  Android Studio: 3.2 AI-181.5540.7.32.5014246

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

**Comment by lovebing** [comment]
我把 
`compileOnly 'com.facebook.react:react-native:+` 
改为 
`compileOnly 'com.facebook.react:react-native:+ `
了，应该可以编译了

**Comment by aLexdcl** [comment]
react-native 0.57, 编译出错 
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':react-native-baidu-map:debugCompileClasspath'.
> Could not find com.facebook.react:react-native:0.56.0.
  Searched in the following locations:
      file:/D:/SDK/android-sdk-windows/extras/m2repository/com/facebook/react/react-native/0.56.0/react-native-0.56.0.pom
      file:/D:/SDK/android-sdk-windows/extras/m2repository/com/facebook/react/react-native/0.56.0/react-native-0.56.0.jar
      file:/D:/SDK/android-sdk-windows/extras/google/m2repository/com/facebook/react/react-native/0.56.0/react-native-0.56.0.pom
      file:/D:/SDK/android-sdk-windows/extras/google/m2repository/com/facebook/react/react-native/0.56.0/react-native-0.56.0.jar
      file:/D:/SDK/android-sdk-windows/extras/android/m2repository/com/facebook/react/react-native/0.56.0/react-native-0.56.0.pom
      file:/D:/SDK/android-sdk-windows/extras/android/m2repository/com/facebook/react/react-native/0.56.0/react-native-0.56.0.jar
      file:/E:/mavenRepository/com/facebook/react/react-native/0.56.0/react-native-0.56.0.pom
      file:/E:/mavenRepository/com/facebook/react/react-native/0.56.0/react-native-0.56.0.jar
      https://dl.google.com/dl/android/maven2/com/facebook/react/react-native/0.56.0/react-native-0.56.0.pom
      https://dl.google.com/dl/android/maven2/com/facebook/react/react-native/0.56.0/react-native-0.56.0.jar
      https://jcenter.bintray.com/com/facebook/react/react-native/0.56.0/react-native-0.56.0.pom
      https://jcenter.bintray.com/com/facebook/react/react-native/0.56.0/react-native-0.56.0.jar
      file:/D:/jsSpace/AwesomeProject/node_modules/react-native/android/com/facebook/react/react-native/0.56.0/react-native-0.56.0.pom
      file:/D:/jsSpace/AwesomeProject/node_modules/react-native/android/com/facebook/react/react-native/0.56.0/react-native-0.56.0.jar
      file:/D:/jsSpace/AwesomeProject/node_modules/react-native-baidu-map/android/usr/local/node/lib/node_modules/react-native/android/com/facebook/react/react-native/0.56.0/react-native-0.56.0.pom
      file:/D:/jsSpace/AwesomeProject/node_modules/react-native-baidu-map/android/usr/local/node/lib/node_modules/react-native/android/com/facebook/react/react-native/0.56.0/react-native-0.56.0.jar
  Required by:
      project :react-native-baidu-map

**Comment by suwu150** [comment]
现在能够导入了,但我进行尝试运行到虚拟机上面的时候,出现了下面的错误信息
```
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/suwu150/WebStormProject/FLS_MW_APP/node_modules/react-native-baidu-map/android/build/intermediates/intermediate-jars/debug/classes.jar
        at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.launchProcessing(DexArchiveBuilderTransform.java:550)
        at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.lambda$convertToDexArchive$1(DexArchiveBuilderTransform.java:488)
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Error while dexing org/lovebing/reactnative/baidumap/view/OverlayMarker.class
The dependency contains Java 8 bytecode. Please enable desugaring by adding the following to build.gradle
android {
    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
}

```

**Comment by 2207345508** [comment]
我也遇到了同样的问题，有人解决了吗？@suwu150

**Comment by suwu150** [comment]
还没有呢

**Comment by 2207345508** [comment]
@aLexdcl 这位兄台解决了嘛？

**Comment by MonkeyInWind** [comment]
+1

**Comment by aLexdcl** [comment]
> 我也遇到了同样的问题，有人解决了吗？@ suwu150

换一个   react-native-baidumap-sdk 这个0.57 亲测能用

**Comment by 2207345508** [comment]
@aLexdcl 多谢兄台

**Comment by tiyunchen** [comment]
> > 我也遇到了同样的问题，有人解决了吗？@ suwu150
> 
> 换一个 react-native-baidumap-sdk 这个0.57 亲测能用

这个这么换

**Comment by xcinnocence** [comment]
project/node_modules/react-native-baidu-map build.gradle, url: 'hhtp-XXX' => 'https=XXX'.
