### ISSUE TITLE
Demo跑不起来 找不到  AndroidManifest.xml 但确实存在

### ISSUE THREAD

**Issue by ElephantCushion** [lovebing/react-native-baidu-map#224]
VinMac:react-native-baidu-map-master Vin$ react-native run-android
Starting JS server...

ENOENT: no such file or directory, open 'app/src/main/AndroidManifest.xml'

Error: ENOENT: no such file or directory, open 'app/src/main/AndroidManifest.xml'
    at Object.openSync (fs.js:450:3)
    at Object.readFileSync (fs.js:350:35)
    at buildAndRun (/Users/Vin/Downloads/react-native-baidu-map-master/node_modules/react-native/local-cli/runAndroid/runAndroid.js:112:3)
    at isPackagerRunning.then.result (/Users/Vin/Downloads/react-native-baidu-map-master/node_modules/react-native/local-cli/runAndroid/runAndroid.js:65:12)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="org.lovebing.reactnative.baidumap">

    <application>
        <service android:name="com.baidu.location.f" android:enabled="true" android:process=":remote">
        </service>
    </application>
</manifest> 
 manifest 缺少东西不全，不对不对？

**Comment by weikilla** [comment]
如果你要跑example，需要进入example文件夹在run
