### ISSUE TITLE
java.lang.NoClassDefFoundError: org.lovebing.reactnative.baidumap.uimanager.MapViewManager

### ISSUE THREAD

**Issue by jkd5170** [lovebing/react-native-baidu-map#241]
java.lang.NoClassDefFoundError: org.lovebing.reactnative.baidumap.uimanager.MapViewManager
	at org.lovebing.reactnative.baidumap.BaiduMapPackage.createViewManagers(BaiduMapPackage.java:45)
	at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:770)
	at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:170)
	at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:53)
	at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:128)
	at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:125)
	at com.facebook.react.LazyReactPackage$2$1.next(LazyReactPackage.java:102)
	at com.facebook.react.LazyReactPackage$2$1.next(LazyReactPackage.java:89)
	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:44)
	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1212)
	at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1182)
	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1120)
	at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:123)
	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:943)
	at java.lang.Thread.run(Thread.java:841)

**Comment by guohuihot** [comment]
我也是这个问题
