### ISSUE TITLE
运行作者的demo,直接报错：unfortunaltely rn have stop !

### ISSUE THREAD

**Issue by tenya** [lovebing/react-native-baidu-map#52]
![image](https://cloud.githubusercontent.com/assets/4264275/22232797/ae1e86de-e226-11e6-9f53-8d4fa0673454.png)
日志如下错误：
01-23 22:13:59.423  2094  2135 I ReactNativeJS: Running application "rn" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
01-23 22:13:59.456  2094  2136 I LibraryLoader: Time to load native libraries: 121 ms (timestamps 7611-7732)
01-23 22:13:59.461  2094  2136 I LibraryLoader: Expected native library version number "",actual native library version number ""
01-23 22:13:59.523  2094  2136 W art     : Attempt to remove non-JNI local reference, dumping thread
01-23 22:13:59.773  2094  2136 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextShadowNode 01-23 22:14:00.225  2094  2155 D         : HostConnection::get() New Host Connection established 0xdd76eb30, tid 2155
01-23 22:14:00.293  2094  2155 E AndroidRuntime: FATAL EXCEPTION: GLThread 165
01-23 22:14:00.293  2094  2155 E AndroidRuntime: Process: com.rn, PID: 2094
01-23 22:14:00.293  2094  2155 E AndroidRuntime: java.lang.IllegalArgumentException: No config chosen
01-23 22:14:00.293  2094  2155 E AndroidRuntime:        at android.opengl.GLSurfaceView$BaseConfigChooser.chooseConfig(GLSurfaceView.java:870)
01-23 22:14:00.293  2094  2155 E AndroidRuntime:        at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1024)
01-23 22:14:00.293  2094  2155 E AndroidRuntime:        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1401)
01-23 22:14:00.293  2094  2155 E AndroidRuntime:        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
01-23 22:14:00.351  1012  1024 W ActivityManager:   Force finishing activity com.rn/.MainActivity
01-23 22:14:00.386   992  1011 D PermissionCache: checking android.permission.READ_FRAME_BUFFER for uid=1000 => granted (6009 us)
01-23 22:14:00.450  1012  1024 D         : HostConnection::get() New Host Connection established 0xdbabde30, tid 1024
01-23 22:14:00.517   992   992 E EGL_emulation: tid 992: eglCreateSyncKHR(1215): error 0x3004 (EGL_BAD_ATTRIBUTE)
01-23 22:14:00.778  1012  1553 W art     : Long monitor contention event with owner method=android.graphics.Bitmap com.android.server.wm.WindowManagerService.screenshotApplicationsInner(android.os.IBinder, int, int, int, boolean) from WindowManagerService.java:6223 waiters=0 for 333ms
01-23 22:14:00.800  1012  1143 W art     : Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.crashApplication(com.android.server.am.ProcessRecord, android.app.ApplicationErrorReport$CrashInfo) from ActivityManagerService.java:12502 waiters=1 for 423ms
01-23 22:14:00.928  1012  1022 I art     : Background partial concurrent mark sweep GC freed 18553(1415KB) AllocSpace objects, 7(140KB) LOS objects, 33% free, 6MB/9MB, paused 20.360ms total 150.467ms
01-23 22:14:00.989  1012  2164 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
01-23 22:14:01.046  1012  1026 I ActivityManager: Killing 1752:com.android.dialer/u0a5 (adj 15): empty #17
01-23 22:14:01.097  1012  2164 I OpenGLRenderer: Initialized EGL, version 1.4
01-23 22:14:01.098  1012  2164 D         : HostConnection::get() New Host Connection established 0xdbabd820, tid 2164
01-23 22:14:01.261  1358  1570 W EGL_emulation: eglSurfaceAttrib not implemented
01-23 22:14:01.261  1358  1570 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xec9672e0, error=EGL_SUCCESS
01-23 22:14:01.269  2094  2124 E Surface : getSlotFromBufferLocked: unknown buffer: 0xf2cb9d90
01-23 22:14:01.509  1012  2164 W EGL_emulation: eglSurfaceAttrib not implemented
01-23 22:14:01.510  1012  2164 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xdb0a48e0, error=EGL_SUCCESS
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
我的环境是，genymotion 2.8.1, android 6.0的。有谁可以帮忙看看是什么原因么。

**Comment by tenya** [comment]
之前以为是，baidu-key问题，现在看来不是。

**Comment by qb1515751487** [comment]
我也碰到一样的问题，请问解决了吗？

**Comment by tenya** [comment]
没解决，只好弃用

**Comment by lovebing** [comment]
我周末看一下是什么原因

**Comment by yummyLcj** [comment]
使用genymotion同直接闪退，在真机情况下调试是可以正常使用的

**Comment by chuxini** [comment]
@yummyLcj 我这边真机也闪退。

**Comment by yummyLcj** [comment]
看一下代码有没有错，我加了这个库以后只要红屏直接闪退，不红屏就没事@chuxini

**Comment by MartinWebDev** [comment]
Any fix yet?
I am doing some react-native work for a company in Shenzhen and they really want to get Baidu Map support :)

**Comment by MartinWebDev** [comment]
After some Googling, I believe this is an OpenGL hardware acceleration issue. So presumably not something the project can control, as I guess it's a hardware issue with the computer itself. 

I changed my Android Virtual Device to use Software graphics not Hardware, and then the map will no longer crash the app in the emulator however it still doesn't work properly. 
Can see the markers, but the map itself will not render, either in Normal mode or Satellite mode. 
![doesnotrendermap](https://cloud.githubusercontent.com/assets/2131908/26387088/78c1c6f8-407d-11e7-9ab8-16176e7b8234.jpg)

And this is probably unrelated, but you can't click any of the buttons either, the properties appear to be read only, so updating the state values causes error. 
![errorswhenupdating](https://cloud.githubusercontent.com/assets/2131908/26387112/978eab3c-407d-11e7-9463-cc684f4d9331.jpg)

**Comment by perfecten** [comment]
AVD Manager.exe 的虚拟机上可以运动Demo，看的到地图
